"""``manage.py aiodrf_convert``: source for the other side, readable and checked."""

import datetime
import enum
import shutil
import subprocess
import sys
import textwrap
from io import StringIO
from pathlib import Path
from typing import Annotated, Literal

import msgspec
import pytest
from django.core.management import CommandError, call_command
from django.core.validators import MaxLengthValidator, RegexValidator
from django.db import models
from django.test.utils import isolate_apps
from pydantic import AfterValidator, BaseModel, Field, Strict, ValidationError
from rest_framework import serializers

from aiodrf.contrib import convert

TODO = convert.TODO

# -- Sources ------------------------------------------------------------------


class ArticleSerializer(serializers.Serializer):
    title = serializers.CharField(max_length=10, min_length=2, trim_whitespace=False)
    pages = serializers.IntegerField(min_value=1, max_value=100, default=5)
    status = serializers.ChoiceField(choices=["draft", "published"])
    tags = serializers.ListField(
        child=serializers.CharField(max_length=5), allow_empty=False
    )
    rating = serializers.FloatField(required=False, allow_null=True)
    code = serializers.RegexField(r"^[A-Z]{3}$", trim_whitespace=False)


class OwnerSerializer(serializers.Serializer):
    name = serializers.CharField(max_length=20)


class BookSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    title = serializers.CharField(max_length=200)
    owner = OwnerSerializer()
    editors = OwnerSerializer(many=True, required=False)
    score = serializers.SerializerMethodField()
    secret = serializers.CharField(write_only=True)

    def get_score(self, book):
        return 1

    def validate_title(self, value):
        return value


class Item(BaseModel):
    name: str = Field(min_length=1, max_length=10)
    qty: int = Field(default=1, ge=1, le=10)
    kind: Literal["a", "b"]
    tags: list[Annotated[str, Field(max_length=3)]] = []
    note: str | None = None


class Part(msgspec.Struct, kw_only=True):
    name: Annotated[str, msgspec.Meta(min_length=1, max_length=10)]
    qty: Annotated[int, msgspec.Meta(ge=1, le=10)] = 1
    kind: Literal["a", "b"]
    note: str | msgspec.UnsetType = msgspec.UNSET


def generate(source, to, name=None):
    if isinstance(source, type) and issubclass(source, serializers.BaseSerializer):
        schemas = convert.from_serializer(source(), name)
        writer = convert.to_pydantic if to == "pydantic" else convert.to_msgspec
        return writer(schemas, "tests.test_convert.X")
    reader = (
        convert.from_pydantic if issubclass(source, BaseModel) else convert.from_msgspec
    )
    return convert.to_drf(reader(source, name), "tests.test_convert.X")


def load(source):
    namespace = {}
    exec(compile(source, "<generated>", "exec"), namespace)  # noqa: S102 -- the code under test
    return namespace


# -- The text -------------------------------------------------------------------


def test_serializer_to_pydantic_splits_input_and_output_and_marks_what_is_not_converted():
    assert generate(BookSerializer, "pydantic") == textwrap.dedent('''\
        """Generated by ``manage.py aiodrf_convert`` from ``tests.test_convert.X``."""

        from typing import Annotated, Any

        from pydantic import BaseModel, Field


        class Owner(BaseModel):
            # DRF strips surrounding whitespace from name before validating; these fields do not.
            name: Annotated[str, Field(min_length=1, max_length=20)]


        class BookIn(BaseModel):
            # TODO(aiodrf_convert): BookSerializer.validate_title() is not converted.
            # DRF strips surrounding whitespace from title, secret before validating; these fields do not.
            title: Annotated[str, Field(min_length=1, max_length=200)]
            owner: Owner
            # DRF: optional but not nullable; None stands for a missing value.
            editors: list[Owner] | None = None
            secret: Annotated[str, Field(min_length=1)]


        class BookOut(BaseModel):
            # TODO(aiodrf_convert): BookSerializer.validate_title() is not converted.
            id: int
            title: Annotated[str, Field(min_length=1, max_length=200)]
            owner: Owner
            editors: list[Owner]
            # TODO(aiodrf_convert): SerializerMethodField is not converted.
            score: Any
        ''')


def test_serializer_to_msgspec_uses_unset_for_optional_fields():
    source = generate(ArticleSerializer, "msgspec")
    assert source == textwrap.dedent('''\
        """Generated by ``manage.py aiodrf_convert`` from ``tests.test_convert.X``."""

        from typing import Annotated, Literal

        import msgspec

        ArticleTags = Annotated[
            list[Annotated[str, msgspec.Meta(min_length=1, max_length=5)]],
            msgspec.Meta(min_length=1),
        ]


        class Article(msgspec.Struct, kw_only=True):
            # DRF strips surrounding whitespace from tags before validating; these fields do not.
            title: Annotated[str, msgspec.Meta(min_length=2, max_length=10)]
            pages: Annotated[int, msgspec.Meta(ge=1, le=100)] = 5
            status: Literal["draft", "published"]
            tags: ArticleTags
            rating: float | msgspec.UnsetType | None = msgspec.UNSET
            code: Annotated[str, msgspec.Meta(min_length=1, pattern="^[A-Z]{3}$")]
        ''')


def test_pydantic_to_serializer():
    assert generate(Item, "drf") == textwrap.dedent('''\
        """Generated by ``manage.py aiodrf_convert`` from ``tests.test_convert.X``."""

        from rest_framework import serializers


        class ItemSerializer(serializers.Serializer):
            name = serializers.CharField(max_length=10, min_length=1, trim_whitespace=False)
            qty = serializers.IntegerField(min_value=1, max_value=10, required=False, default=1)
            kind = serializers.ChoiceField(choices=["a", "b"])
            tags = serializers.ListField(
                child=serializers.CharField(
                    max_length=3, allow_blank=True, trim_whitespace=False
                ),
                required=False,
                default=list,
            )
            note = serializers.CharField(
                allow_blank=True,
                trim_whitespace=False,
                allow_null=True,
                required=False,
                default=None,
            )
        ''')


def test_msgspec_to_serializer_keeps_wire_names():
    class Renamed(msgspec.Struct, rename="camel"):
        page_count: int

    assert 'pageCount = serializers.IntegerField(source="page_count")' in generate(
        Renamed, "drf"
    )
    assert (
        "note = serializers.CharField(\n        allow_blank=True, trim_whitespace=False, required=False\n    )"
        in (generate(Part, "drf"))
    )


def test_what_cannot_be_expressed_is_marked_not_guessed():
    class Odd(BaseModel):
        values: set[int]
        either: int | str

    source = generate(Odd, "drf")
    assert "# TODO(aiodrf_convert): set[int] is not converted." in source
    assert "values = serializers.JSONField()" in source
    assert "# TODO(aiodrf_convert): the union int | str is not converted." in source

    class Decimals(serializers.Serializer):
        price = serializers.DecimalField(max_digits=6, decimal_places=2)
        file = serializers.FileField()

    msgspec_source = generate(Decimals, "msgspec")
    assert (
        "max_digits, decimal_places cannot be expressed with msgspec.Meta"
        in msgspec_source
    )
    assert (
        "# TODO(aiodrf_convert): FileField is not converted.\n    file: Any"
        in msgspec_source
    )
    assert "Field(max_digits=6, decimal_places=2)" in generate(Decimals, "pydantic")


def test_long_types_are_named_so_the_lines_fit():
    class Long(serializers.Serializer):
        status = serializers.ChoiceField(
            choices=[f"state-number-{n}" for n in range(12)]
        )

    source = generate(Long, "pydantic")
    assert "LongStatus = Literal[" in source
    assert "    status: LongStatus\n" in source
    load(source)


@pytest.mark.skipif(
    shutil.which("ruff") is None
    and not (Path(sys.executable).parent / "ruff").exists(),
    reason="ruff is not installed",
)
@pytest.mark.parametrize(
    ("source", "to"),
    [
        (ArticleSerializer, "pydantic"),
        (ArticleSerializer, "msgspec"),
        (BookSerializer, "pydantic"),
        (BookSerializer, "msgspec"),
        (Item, "drf"),
        (Part, "drf"),
    ],
)
def test_the_generated_code_is_formatted_and_lint_clean(source, to, tmp_path):
    ruff = shutil.which("ruff") or str(Path(sys.executable).parent / "ruff")
    config = str(Path(__file__).resolve().parent.parent / "pyproject.toml")
    path = tmp_path / "generated.py"
    path.write_text(generate(source, to))
    for command in (["format", "--check"], ["check"]):
        result = subprocess.run(
            [ruff, *command, "--config", config, str(path)],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, result.stdout + result.stderr


# -- The meaning ----------------------------------------------------------------

ARTICLES = [
    {"title": "ok", "status": "draft", "tags": ["a"], "code": "ABC"},
    {"title": "o", "status": "draft", "tags": ["a"], "code": "ABC"},
    {"title": "x" * 11, "status": "draft", "tags": ["a"], "code": "ABC"},
    {"status": "draft", "tags": ["a"], "code": "ABC"},
    {"title": "ok", "pages": 0, "status": "draft", "tags": ["a"], "code": "ABC"},
    {"title": "ok", "pages": 101, "status": "draft", "tags": ["a"], "code": "ABC"},
    {"title": "ok", "pages": 100, "status": "draft", "tags": ["a"], "code": "ABC"},
    {"title": "ok", "status": "gone", "tags": ["a"], "code": "ABC"},
    {"title": "ok", "status": "draft", "tags": [], "code": "ABC"},
    {"title": "ok", "status": "draft", "tags": ["abcdef"], "code": "ABC"},
    {"title": "ok", "status": "draft", "tags": ["a"], "rating": None, "code": "ABC"},
    {"title": "ok", "status": "draft", "tags": ["a"], "rating": 2.5, "code": "ABC"},
    {"title": "ok", "status": "draft", "tags": ["a"], "code": "abc"},
    {"title": "ok", "status": "draft", "tags": ["a"], "code": "ABCD"},
]


def drf_accepts(serializer_class, data):
    return serializer_class(data=data).is_valid()


@pytest.mark.parametrize("data", ARTICLES)
def test_the_pydantic_model_accepts_what_the_serializer_accepts(data):
    model = load(generate(ArticleSerializer, "pydantic"))["Article"]
    try:
        instance = model.model_validate(data)
    except ValidationError:
        accepted = False
    else:
        accepted = True
        assert instance.pages == data.get("pages", 5)
    assert accepted == drf_accepts(ArticleSerializer, data)


@pytest.mark.parametrize("data", ARTICLES)
def test_the_msgspec_struct_accepts_what_the_serializer_accepts(data):
    struct = load(generate(ArticleSerializer, "msgspec"))["Article"]
    try:
        msgspec.convert(data, struct)
    except msgspec.ValidationError:
        accepted = False
    else:
        accepted = True
    assert accepted == drf_accepts(ArticleSerializer, data)


ITEMS = [
    {"name": "x", "kind": "a"},
    {"name": "", "kind": "a"},
    {"name": " spaced ", "kind": "a"},
    {"name": "x" * 11, "kind": "a"},
    {"kind": "a"},
    {"name": "x", "kind": "c"},
    {"name": "x", "kind": "a", "qty": 0},
    {"name": "x", "kind": "a", "qty": 11},
    {"name": "x", "kind": "a", "qty": 10},
    {"name": "x", "kind": "a", "tags": ["abc"]},
    {"name": "x", "kind": "a", "tags": ["abcd"]},
    {"name": "x", "kind": "a", "note": None},
    {"name": "x", "kind": "a", "note": ""},
]


@pytest.mark.parametrize("data", ITEMS)
def test_the_serializer_accepts_what_the_pydantic_model_accepts(data):
    serializer_class = load(generate(Item, "drf"))["ItemSerializer"]
    try:
        Item.model_validate(data)
    except ValidationError:
        accepted = False
    else:
        accepted = True
    assert drf_accepts(serializer_class, data) == accepted


@pytest.mark.parametrize(
    "data", [{k: v for k, v in item.items() if k != "tags"} for item in ITEMS]
)
def test_the_serializer_accepts_what_the_msgspec_struct_accepts(data):
    serializer_class = load(generate(Part, "drf"))["PartSerializer"]
    try:
        msgspec.convert(data, Part)
    except msgspec.ValidationError:
        accepted = False
    else:
        accepted = True
    assert drf_accepts(serializer_class, data) == accepted


def test_nested_classes_come_first_and_round_trip():
    namespace = load(generate(BookSerializer, "pydantic"))
    book = namespace["BookIn"].model_validate(
        {"title": "T", "owner": {"name": "Ann"}, "secret": "s"}
    )
    assert book.owner.name == "Ann"


# -- The command ------------------------------------------------------------------


def test_the_command_writes_to_standard_output_and_to_a_file(tmp_path):
    out = StringIO()
    call_command("aiodrf_convert", "tests.test_convert.Item", "--to", "drf", stdout=out)
    assert out.getvalue() == generate(Item, "drf").replace(
        "tests.test_convert.X", "tests.test_convert.Item"
    )

    target = tmp_path / "schemas.py"
    call_command(
        "aiodrf_convert",
        "tests.test_convert.ArticleSerializer",
        "--to",
        "pydantic",
        "--name",
        "Post",
        "--output",
        str(target),
        stdout=StringIO(),
    )
    assert "class Post(BaseModel):" in target.read_text()


@pytest.mark.parametrize(
    ("path", "to", "message"),
    [
        ("tests.test_convert.Missing", "drf", "Cannot import"),
        ("tests.test_convert.generate", "drf", "is not a class"),
        ("tests.test_convert.drf_accepts", "drf", "is not a class"),
        ("tests.test_convert.StringIO", "drf", "neither a DRF serializer"),
        ("tests.test_convert.ArticleSerializer", "drf", "already a DRF serializer"),
        ("tests.test_convert.Item", "msgspec", "use --to drf"),
    ],
)
def test_the_command_refuses_what_it_cannot_convert(path, to, message):
    with pytest.raises(CommandError, match=message):
        call_command("aiodrf_convert", path, "--to", to, stdout=StringIO())


def test_a_serializer_that_needs_arguments_is_reported():
    with pytest.raises(CommandError, match="cannot be instantiated"):
        call_command(
            "aiodrf_convert",
            "tests.test_convert.NeedsContext",
            "--to",
            "pydantic",
            stdout=StringIO(),
        )


class Broken(serializers.Serializer):
    def __init__(self, *args, **kwargs):
        raise ValueError("a broken field")


def test_a_serializer_failing_on_its_own_is_reported_with_its_error():
    with pytest.raises(CommandError, match="ValueError: a broken field") as caught:
        call_command("aiodrf_convert", "tests.test_convert.Broken", "--to", "msgspec")
    assert "without arguments" not in str(caught.value)


class NeedsContext(serializers.Serializer):
    def __init__(self, *args, owner, **kwargs):
        super().__init__(*args, **kwargs)


def test_converting_a_pydantic_model_does_not_import_msgspec():
    code = """
        import sys
        import django
        from django.conf import settings
        settings.configure(INSTALLED_APPS=["rest_framework"])
        django.setup()
        from pydantic import BaseModel
        from aiodrf.contrib import convert
        class Example(BaseModel):
            value: int
        assert "IntegerField" in convert.to_drf(convert.from_pydantic(Example), "x.Example")
        assert "msgspec" not in sys.modules
    """
    root = Path(__file__).resolve().parent.parent
    result = subprocess.run(
        [sys.executable, "-c", textwrap.dedent(code)],
        env={"PYTHONPATH": f"{root / 'src'}:{root}", "PATH": ""},
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr


def test_model_serializer_relations_become_primary_key_types():
    from tests.testapp.serializers import BookSerializer as ModelBookSerializer

    source = convert.to_pydantic(
        convert.from_serializer(ModelBookSerializer()), "x.Book"
    )
    assert "    author: int\n" in source
    assert "    tags: list[int] | None = None\n" in source
    assert (
        "# TODO(aiodrf_convert): validator UniqueValidator is not converted." in source
    )
    # The model's default is applied when saving, so DRF leaves the field optional.
    assert "    pages: Annotated[int, Field(ge=0, le=" in source
    assert "] | None = None\n" in source


def _generated_serializer(model):
    namespace = {}
    exec(convert.to_drf(convert.from_pydantic(model), "tests.Account"), namespace)  # noqa: S102 -- generated here
    return namespace[f"{model.__name__}Serializer"]


def test_an_excluded_pydantic_field_is_write_only():
    class Account(BaseModel):
        name: str
        password: str = Field(exclude=True)

    source = convert.to_drf(convert.from_pydantic(Account), "tests.Account")
    assert (
        "password = serializers.CharField(\n        allow_blank=True, trim_whitespace=False, write_only=True\n    )"
        in source
    )
    serializer_class = _generated_serializer(Account)
    # The generated serializer keeps the model's output safe.
    assert serializer_class({"name": "u", "password": "secret"}).data == {"name": "u"}
    accepted = serializer_class(data={"name": "u", "password": "secret"})
    assert accepted.is_valid(), accepted.errors
    assert accepted.validated_data == {"name": "u", "password": "secret"}


def test_output_customizations_of_a_pydantic_model_are_marked():
    from pydantic import computed_field, field_serializer
    from pydantic.fields import FieldInfo

    # exclude_if is new in pydantic 2.11; the oldest supported is 2.7.
    has_exclude_if = "exclude_if" in FieldInfo.__slots__
    token_field = (
        Field(exclude_if=lambda value: not value) if has_exclude_if else Field()
    )

    class Account(BaseModel):
        name: str = Field(serialization_alias="login")
        token: str = token_field

        @field_serializer("name")
        def shout(self, value):
            return value.upper()

        @computed_field
        @property
        def initial(self) -> str:
            return self.name[:1]

    source = convert.to_drf(convert.from_pydantic(Account), "tests.Account")
    todos = [
        line.strip() for line in source.splitlines() if "TODO(aiodrf_convert)" in line
    ]
    assert any("'login'" in line for line in todos), todos
    assert any("exclude_if" in line for line in todos) == has_exclude_if, todos
    assert any("shout()" in line for line in todos), todos
    assert any("initial" in line for line in todos), todos


# -- Validators and names the conversion must not drop silently -----------------


class ExplicitValidatorsSerializer(serializers.Serializer):
    code = serializers.CharField(validators=[RegexValidator(r"^\d+$")])
    short = serializers.CharField(max_length=5, validators=[MaxLengthValidator(3)])
    plain = serializers.CharField(max_length=5)


@pytest.mark.parametrize("to", ["pydantic", "msgspec"])
def test_explicit_field_validators_are_marked(to):
    source = generate(ExplicitValidatorsSerializer, to)
    assert f"{TODO} validator RegexValidator is not converted." in source
    assert f"{TODO} validator MaxLengthValidator is not converted." in source
    # The validators DRF builds from the options are the options, converted.
    assert source.count(TODO) == 2, source


@isolate_apps("tests.testapp")
def test_the_validators_modelserializer_generates_are_marked():
    class Pair(models.Model):
        a = models.IntegerField()
        b = models.IntegerField()

        class Meta:
            app_label = "testapp"
            unique_together = [("a", "b")]

        def __str__(self):
            return f"{self.a}, {self.b}"

    class PairSerializer(serializers.ModelSerializer):
        class Meta:
            model = Pair
            fields = ["a", "b"]

    assert PairSerializer().validators  # DRF's, from unique_together
    source = generate(PairSerializer, "pydantic")
    assert (
        f"{TODO} PairSerializer's validator UniqueTogetherValidator is not converted."
        in source
    )


class UnderscoreSerializer(serializers.Serializer):
    _id = serializers.CharField()


def test_a_field_name_pydantic_would_make_private_gets_an_alias():
    model = load(generate(UnderscoreSerializer, "pydantic"))["Underscore"]
    instance = model.model_validate({"_id": "x"})
    assert instance.model_dump(by_alias=True) == {"_id": "x"}
    struct = load(generate(UnderscoreSerializer, "msgspec"))["Underscore"]
    assert msgspec.json.decode(b'{"_id": "x"}', type=struct) == struct(_id="x")


class BlankSerializer(serializers.Serializer):
    code = serializers.CharField(allow_blank=True, min_length=3)
    tag = serializers.RegexField(r"^[a-z]+$", allow_blank=True)


@pytest.mark.parametrize("to", ["pydantic", "msgspec"])
def test_the_blank_string_drf_accepts_is_accepted(to):
    data = {"code": "", "tag": ""}
    assert BlankSerializer(data=data).is_valid()
    source = generate(BlankSerializer, to)
    schema = load(source)["Blank"]
    if to == "pydantic":
        schema(**data)
        with pytest.raises(ValidationError):
            schema(code="", tag="A")
    else:
        msgspec.convert(data, schema)
    assert f"{TODO} min_length=3 applies to non-blank values" in source


def _positive(value):
    if value <= 0:
        raise ValueError("not positive")
    return value


class Checked(BaseModel):
    n: Annotated[int, AfterValidator(_positive)]
    when: Annotated[datetime.datetime, Strict()]
    size: Annotated[int, Field(ge=1, description="documented")]


class Aware(msgspec.Struct):
    at: Annotated[datetime.datetime, msgspec.Meta(tz=True, title="x")]


def test_annotated_metadata_that_is_not_a_constraint_is_marked():
    source = generate(Checked, "drf")
    assert f"{TODO} AfterValidator is not converted." in source
    assert f"{TODO} Strict is not converted." in source
    assert "documented" not in source
    assert "min_value=1" in source
    assert f"{TODO} msgspec.Meta(tz=True) is not converted." in generate(Aware, "drf")


class Priority(enum.IntEnum):
    LOW = 1
    HIGH = 2


class Ticket(BaseModel):
    priority: Priority = Priority.LOW


def test_an_int_enum_default_is_its_value():
    serializer = load(generate(Ticket, "drf"))["TicketSerializer"]()
    assert serializer.fields["priority"].default == 1


class BlankEmailSerializer(serializers.Serializer):
    email = serializers.EmailField(allow_blank=True)


def test_a_blank_able_email_field_still_marks_its_format():
    source = generate(BlankEmailSerializer, "pydantic")
    assert f"{TODO} EmailField format validation is not converted." in source


# -- Review findings -------------------------------------------------------------


class Tree(BaseModel):
    name: str
    children: list["Tree"] = []


class Left(BaseModel):
    right: "Right | None" = None


class Right(BaseModel):
    left: Left | None = None


Left.model_rebuild()


@pytest.mark.parametrize("model", [Tree, Left])
def test_a_recursive_reference_is_marked_and_the_module_imports(model):
    source = generate(model, "drf")
    namespace = load(source)
    assert f"{model.__name__}Serializer" in namespace
    assert "recursive" in source


def test_an_empty_collection_default_is_a_valid_msgspec_default():
    class EmptySerializer(serializers.Serializer):
        tags = serializers.ListField(child=serializers.CharField(), default=[])
        extra = serializers.DictField(default={})

    struct = load(generate(EmptySerializer, "msgspec"))["Empty"]
    first, second = struct(), struct()
    assert first.tags == []
    assert first.extra == {}
    assert first.tags is not second.tags


class Picky(serializers.Serializer):
    a = serializers.CharField()
    b = serializers.CharField()

    def __init__(self, *args, keep=None, **kwargs):
        super().__init__(*args, **kwargs)
        for name in set(self.fields) - set(keep or self.fields):
            self.fields.pop(name)


class TwoPickySerializer(serializers.Serializer):
    first = Picky(keep=["a"])
    second = Picky(keep=["b"])


def test_nested_instances_of_one_class_with_other_fields_stay_apart():
    namespace = load(generate(TwoPickySerializer, "pydantic"))
    two = namespace["TwoPicky"]
    first = two.model_fields["first"].annotation
    second = two.model_fields["second"].annotation
    assert set(first.model_fields) == {"a"}
    assert set(second.model_fields) == {"b"}


def test_a_nested_class_used_twice_is_written_once():
    class OwnersSerializer(serializers.Serializer):
        first = OwnerSerializer()
        second = OwnerSerializer()

    source = generate(OwnersSerializer, "pydantic")
    assert "class Owner2" not in source


def test_unconverted_settings_beside_a_constraint_are_marked():
    from pydantic import StringConstraints

    class Stripped(BaseModel):
        code: Annotated[str, StringConstraints(pattern="^a", strip_whitespace=True)]

    source = generate(Stripped, "drf")
    assert "regex=" in source
    assert f"{TODO} StringConstraints(strip_whitespace=True) is not converted." in (
        source
    )


class Raw(msgspec.Struct):
    kind: Literal[b"x", "y"]


def test_a_literal_without_source_is_marked_not_raised():
    source = generate(Raw, "drf")
    assert "serializers.JSONField()" in source
    assert f"{TODO} the choices" in source
    load(source)


def test_non_finite_floats_are_valid_source():
    class Bounded(BaseModel):
        low: float = float("-inf")
        high: Annotated[float, Field(le=float("inf"))] = float("inf")

    serializer = load(generate(Bounded, "drf"))["BoundedSerializer"]()
    assert serializer.fields["low"].default == float("-inf")
    assert serializer.fields["high"].max_value == float("inf")


def test_a_dict_minimum_above_one_is_marked():
    class Pairs(BaseModel):
        one: dict[str, int] = Field(min_length=1)
        two: dict[str, int] = Field(min_length=2)

    source = generate(Pairs, "drf")
    serializer = load(source)["PairsSerializer"]()
    assert serializer.fields["one"].allow_empty is False
    assert serializer.fields["two"].allow_empty is True
    assert f"{TODO} the constraint min_length is not converted." in source


class Maybe(BaseModel):
    parts: list[Item | None]
    both: list[Item | None] | None


def test_null_list_items_of_a_nested_schema_are_marked():
    source = generate(Maybe, "drf")
    assert source.count(f"{TODO} null items") == 1
    serializer = load(source)["MaybeSerializer"]()
    assert serializer.fields["both"].allow_null
    assert serializer.fields["both"].child.allow_null


class EmptyChoiceSerializer(serializers.Serializer):
    kind = serializers.ChoiceField(choices=[])


class HiddenSerializer(serializers.Serializer):
    owner = serializers.HiddenField(default=1)


@pytest.mark.parametrize("to", ["pydantic", "msgspec"])
def test_a_choice_field_without_choices_is_marked(to):
    source = generate(EmptyChoiceSerializer, to)
    load(source)
    assert "Literal[]" not in source
    assert "the field has no choices; DRF refuses every value." in source


@pytest.mark.parametrize("to", ["pydantic", "msgspec"])
def test_a_schema_of_notes_only_has_a_body(to):
    load(generate(HiddenSerializer, to))


def _corpus():
    import inspect

    from tests.testapp import serializers as testapp

    modules = [sys.modules[__name__], testapp]
    return sorted(
        {
            value
            for module in modules
            for value in vars(module).values()
            if inspect.isclass(value)
            and issubclass(value, serializers.Serializer)
            and value.__module__ == module.__name__
            # Built without arguments, as the command builds them.
            and "__init__" not in vars(value)
        },
        key=lambda cls: (cls.__module__, cls.__qualname__),
    )


@pytest.mark.parametrize("to", ["pydantic", "msgspec"])
@pytest.mark.parametrize("serializer", _corpus(), ids=lambda cls: cls.__qualname__)
def test_every_generated_module_executes(serializer, to):
    load(generate(serializer, to))


class Accented(serializers.Serializer):
    name = serializers.CharField(help_text="Café ✓")


def test_the_output_file_is_utf_8_whatever_the_locale(tmp_path, monkeypatch):
    # Python reads source as UTF-8; the locale's encoding may not be it
    # (Windows code pages without UTF-8 mode).
    written = []
    original = Path.write_text

    def write_text(self, data, encoding=None, *args, **kwargs):
        written.append(encoding)
        return original(self, data, "utf-8", *args, **kwargs)

    monkeypatch.setattr(Path, "write_text", write_text)
    target = tmp_path / "schemas.py"
    call_command(
        "aiodrf_convert",
        "tests.test_convert.Accented",
        "--to",
        "pydantic",
        "--output",
        str(target),
        stdout=StringIO(),
    )
    assert written == ["utf-8"]
