# Generated by Django 6.1.1 on 2026-09-26 13:10

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("amount", models.IntegerField(db_default=1)),
                (
                    "total",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("amount"), "*", models.Value(2)
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
